"""Unified outbound message contracts and platform renderers."""

from chatdome.outbound.builders import (
    EnvironmentFactsBuilder,
    OutboundMessageBuilder,
    build_approval_details,
    build_approval_request,
    build_notification_message,
    build_sentinel_alert,
    build_environment_message,
)
from chatdome.outbound.models import (
    ActionKind,
    ApprovalDetailsFacts,
    ApprovalRequestFacts,
    CodexAuthorizationFacts,
    CommandEchoFacts,
    CommandHelpFacts,
    CommandHelpItemFacts,
    EnvironmentFacts,
    ModelProfileFacts,
    ModelProfilesFacts,
    OutboundAction,
    OutboundMessage,
    OutboundMessageKind,
    RenderedControl,
    RenderedMessage,
    SessionControlFacts,
    TokenUsageFacts,
)

__all__ = [
    "ActionKind",
    "ApprovalDetailsFacts",
    "ApprovalRequestFacts",
    "CodexAuthorizationFacts",
    "CommandEchoFacts",
    "CommandHelpFacts",
    "CommandHelpItemFacts",
    "EnvironmentFacts",
    "ModelProfileFacts",
    "EnvironmentFactsBuilder",
    "ModelProfilesFacts",
    "OutboundAction",
    "OutboundMessage",
    "OutboundMessageBuilder",
    "OutboundMessageKind",
    "RenderedControl",
    "RenderedMessage",
    "SessionControlFacts",
    "TokenUsageFacts",
    "build_notification_message",
    "build_sentinel_alert",
    "build_approval_details",
    "build_approval_request",
    "build_environment_message",
]
